name: enscribe
description: "Enscribe notes, tasks, and scripture."
publish_to: "none"

version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.3+1
  path: ^1.8.3
  package_info_plus: ^8.3.0
  flutter_staggered_grid_view: ^0.7.0
  material_symbols_icons: ^4.2815.1
  google_fonts: ^6.2.1
  dropdown_button2: ^2.3.9
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: true
  image_path: "assets/icon_full.png"
  adaptive_icon_background: "#673AB7"
  adaptive_icon_foreground: "assets/icon_foreground.png"
  adaptive_icon_foreground_inset: 28

flutter:
  uses-material-design: true
